version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8000
    tty: true
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

volumes:
  postgres_data: