# Generated by Django 4.1.2 on 2022-11-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_written_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='englishnumbers',
            index=models.Index(fields=['number'], name='full_writte_number_2d0341_idx'),
        ),
    ]
